### ISSUE TITLE
Mettre en évidence la première phrase des textes

### ISSUE THREAD

**Issue by matosps** [blirette/schola#19]
Mettre en évidence la première phrase des textes des sections suivantes :

Outils/Introduction ;
Mission/Introduction+contexte ;
Mission/Historique.

Pour ce faire, ajoutez un retour de paragraphe après la phrase en question (sans espacement ajouté) et changez le style de la typographie pour bold. Gardez la même taille de police du reste du texte.

Veuillez prendre les instructions ci-dessous en considération. 

<img width="646" alt="capture d ecran 2018-02-14 a 15 34 26" src="https://user-images.githubusercontent.com/36485979/36284671-90d1da46-1276-11e8-8b7c-04b3ce98730f.png">
<img width="636" alt="capture d ecran 2018-02-14 a 15 35 13" src="https://user-images.githubusercontent.com/36485979/36284672-90df8722-1276-11e8-8dfa-f089ed1a3ab2.png">
<img width="635" alt="capture d ecran 2018-02-14 a 15 35 21" src="https://user-images.githubusercontent.com/36485979/36284673-90efada0-1276-11e8-9249-784c911fb5b7.png">
<img width="623" alt="capture d ecran 2018-02-14 a 15 35 32" src="https://user-images.githubusercontent.com/36485979/36284674-90fc7ddc-1276-11e8-9ea0-9d334c317644.png">

**Comment by laurencep3** [comment]
Ces changements devraient se faire voir également sur les tuiles d'introduction à la page d'accueil, comme ceci : 

<img width="864" alt="capture d ecran 2018-02-18 a 23 27 51" src="https://user-images.githubusercontent.com/36280664/36362502-6c3bd828-1503-11e8-93b3-fc837f132276.png">

Évidemment la même chose pour la tuile d'introduction à la Mission de Schola.
