### ISSUE TITLE
Coquille dans la case «Comprendre : l'école et ses enjeux»

### ISSUE THREAD

**Issue by blirette** [blirette/schola#2]
Changer:
le rôle des différents utilisateurs d’une école primaire ou secondaire
... par:
le rôle des différent**e**s utilisateurs d’une école primaire ou secondaire

**Comment by blirette** [comment]
Corrigé et mis en ligne. Ne peut vérifier à cause de l'alerte SSL. En attente.

**Comment by frlep1** [comment]
TEst

**Comment by blirette** [comment]
En ligne.
