### ISSUE TITLE
Ajouter champs « Occupation »

### ISSUE THREAD

**Issue by matosps** [blirette/schola#22]
Ajouter un champ «Occupation » dans la section _Suivez-nous !_

Prenez en considération les instructions suivantes pour ce qui est du positionnement du champ à ajouter : 

<img width="620" alt="capture d ecran 2018-02-17 a 16 51 43" src="https://user-images.githubusercontent.com/36485979/36345983-8071b4ee-1403-11e8-8e88-2a0c57d5600f.png">

**Comment by blirette** [comment]
Ajouté.
