### ISSUE TITLE
Remplacer le titre «Schola.ca» par «schola.ca»

### ISSUE THREAD

**Issue by matosps** [blirette/schola#24]
Remplacer le S majuscule du titre de la section de confirmation d'inscription Mailchimp (voir ci-dessous) par un s minuscule : 

<img width="635" alt="capture d ecran 2018-02-17 a 16 59 30" src="https://user-images.githubusercontent.com/36485979/36346035-5565d900-1404-11e8-9bcb-dd024e72ded6.png">

<img width="953" alt="capture d ecran 2018-02-17 a 17 03 17" src="https://user-images.githubusercontent.com/36485979/36346040-8d73feee-1404-11e8-8811-1ca1fa62bb32.png">

**Comment by blirette** [comment]
Corrigé.
