### ISSUE TITLE
Modifier le pudding des sous-titres dans lightbox des outils.

### ISSUE THREAD

**Issue by laurencep3** [blirette/schola#30]
Modifier le padding: 5px 0; pour **padding: 0 0 5px 0;**

<img width="653" alt="capture d ecran 2018-02-19 a 00 17 19" src="https://user-images.githubusercontent.com/36280664/36363337-463ab0ca-150a-11e8-9556-03f8228ba7bf.png">

**Comment by blirette** [comment]
Complément d'information: Laurence n'aime pas le «pudding» :(
