### ISSUE TITLE
Corriger les noms des collaborateurs (Majuscule x Minuscule)

### ISSUE THREAD

**Issue by matosps** [blirette/schola#32]
**Mettre la lettre identifiée ci-dessous en minuscule :**

MANDATAIRES

Ministère de l’Éducation et de l’Enseignement **s**upérieur

**Mettre la lettre identifiée ci-dessous en majuscule :**

MINISTÈRES

Ministère du Développement durable, de l'**E**nvironnement et de la **L**utte contre les changements climatiques 

Ministère de l'**É**ducation et de l'**E**nseignement supérieur

Ministère de la **S**anté et des **S**ervices sociaux

**Comment by blirette** [comment]
Corrigé!
![image](https://user-images.githubusercontent.com/1894507/36998809-2cb923b0-208c-11e8-941f-fab4dfb8d81b.png)
