### ISSUE TITLE
Problème d'accessibilité (5 erreurs) : Ajouter des label aux champs de texte du formulaire.

### ISSUE THREAD

**Issue by fpedneault** [blirette/schola#33]
<img width="423" alt="capture d ecran 2018-02-28 a 10 31 55" src="https://user-images.githubusercontent.com/36019238/37111675-45f667f6-220e-11e8-8233-d29174803507.png">

**Comment by fpedneault** [comment]
Il reste une erreur, mais il s'agit d'un input invisible. Peut-on l'enlever?

**Comment by blirette** [comment]
Je ne crois pas. C'est pour empêcher des «spam» bot. Je recommande de le laisser en place.
