### ISSUE TITLE
Ajouter des retours de lignes sur les titres de boîtes

### ISSUE THREAD

**Issue by blirette** [blirette/schola#5]
Ajouter des retours de lignes sur les titres de boîtes. Rendre le résultat visuel plus intéressant.
![br](https://user-images.githubusercontent.com/1894507/35683976-7974c3a2-0733-11e8-964d-b0d1a329e890.png)

**Comment by fpedneault** [comment]
Je crois que Pablo et Laurence avaient une requête semblable que j'ai résolu.
