### ISSUE TITLE
Désactiver les «toggle» des sections

### ISSUE THREAD

**Issue by blirette** [blirette/schola#6]
Je suggère de désactiver les «toggles» des sections, car cela n'amène rien et crée des problèmes d'affichages.
![toggle](https://user-images.githubusercontent.com/1894507/35684022-a27f12c0-0733-11e8-99b3-2ebe802625df.png)

**Comment by laurencep3** [comment]
**Transformer les «toggles» en zones de titre.**

**Voici les changements apportés au contenu :** 
Retirer le tiret après le titre «Outils».
Retirer le tiret après le titre «Mission».


**Voici les changements apportés au style :**
background-color: #F8F8F8
color: #000000;
font-size: 2.0em;
font-weight: 700;
margin-top: 20px;

**Comment by blirette** [comment]
C'est corrigé.
